# Data Pipeline Configuration
project:
  id: vaulted-timing-473322-f9
  region: us-central1

datasets:
  transactional:
    - financial_anomaly
    - credit_card_fraud
    - ieee_transaction
    - ieee_identity
  
  document:
    - invoice_annotations
    - receipt_forgery
    - receipt_classification

storage:
  buckets:
    invoices: vaulted-timing-473322-f9-invoicedata
    receipts: vaulted-timing-473322-f9-invoicedata
  
  cache:
    enabled: true
    ttl: 3600
    max_size: 1000

feature_engineering:
  enabled_features:
    - temporal_features
    - statistical_features
    - aggregation_features
    - text_features
    - image_features
  
  feature_store:
    dataset: feature_store
    versioning: true
    monitoring: true

ml_frameworks:
  tensorflow:
    version: 2.15.0
    gpu_support: true
  
  pytorch:
    version: 2.1.0
    cuda_version: 12.1
  
  scikit_learn:
    version: 1.3.0

monitoring:
  data_quality:
    enabled: true
    check_frequency: daily
    alert_threshold: 0.1
  
  model_drift:
    enabled: true
    baseline_window: 30
    detection_method: ks_test
  
  performance:
    track_latency: true
    track_throughput: true
    alert_on_degradation: true

streaming:
  pubsub:
    enabled: true
    topics:
      - fraud_detection_stream
      - document_verification_stream
  
  batch_size: 100
  window_size: 60  # seconds

orchestration:
  scheduler: airflow
  dag_location: /dags
  default_retries: 2
  max_parallel_tasks: 10