services:
  # Node.js Frontend (Primary Service on port 3000)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"  # Node.js serves on 3000
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000  # Points to FastAPI
      - REACT_APP_ENVIRONMENT=development
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Anonymous volume for node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Python FastAPI Backend (Secondary Service on port 8000)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # FastAPI serves on 8000
    environment:
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - API_PREFIX=/api
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge

volumes:
  backend_data: