version: '3.8'

services:
  # FastAPI Backend - Development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: invoice-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
    networks:
      - app-network
    restart: unless-stopped
    command: ["uvicorn", "backend.main_docker:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # React Frontend - Development (port 3000)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: invoice-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge