# GitHub Actions workflow for Azure deployment
name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_FRONTEND: 'shellhacks-frontend'
  AZURE_WEBAPP_NAME_BACKEND: 'shellhacks-backend'
  NODE_VERSION: '18.x'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Build React app
      run: |
        cd frontend
        npm run build

    - name: Copy server files
      run: |
        cp server.js frontend/
        cp package.json frontend/
        cp package-lock.json frontend/

    - name: Deploy to Azure Web App (Frontend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: frontend/

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create startup script
      run: |
        echo "#!/bin/bash" > startup.sh
        echo "cd /home/site/wwwroot" >> startup.sh
        echo "python -m uvicorn backend.main_simple:app --host 0.0.0.0 --port 8000" >> startup.sh
        chmod +x startup.sh

    - name: Deploy to Azure Web App (Backend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: .
        startup-command: './startup.sh'