# GitHub Actions workflow for Azure deployment
name: Deploy to Single Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'AgentZero'  # Updated to match your actual app name
  NODE_VERSION: '22.x'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4

    # Build Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Build React app
      run: |
        cd frontend
        npm run build

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Create unified deployment package
    - name: Create deployment package
      run: |
        mkdir -p deploy
        
        # Copy backend Python files (only Python files to avoid Node.js detection)
        cp requirements.txt deploy/
        cp -r backend/* deploy/
        
        # Copy built frontend files to static directory
        mkdir -p deploy/static
        cp -r frontend/build/* deploy/static/
        
        # Create .deployment file to DISABLE Oryx build
        cat > deploy/.deployment << 'EOF'
        [config]
        SCM_DO_BUILD_DURING_DEPLOYMENT=false
        EOF
        
        # Remove any package.json files that might confuse deployment
        find deploy -name "package*.json" -delete || true
        find deploy -name "node_modules" -type d -exec rm -rf {} + || true
        
        # Create startup script for Azure App Service
        cat > deploy/startup.sh << 'EOF'
        #!/bin/bash
        set -e
        echo "🚀 Starting unified FastAPI backend with static frontend..."
        cd /home/site/wwwroot
        
        # Install Python dependencies at runtime
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        # Start the FastAPI application
        python -m uvicorn main:app --host 0.0.0.0 --port 8000
        EOF
        
        chmod +x deploy/startup.sh

    # Azure Login
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88FBF5A58CF4436E8F8955E200248A41 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7DE0416DFB4B4CB88EDDCA0CC26BC123 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AD05817C00C745649FDAAE35BB36A645 }}

    # Disable Oryx build completely
    - name: Configure Azure App Settings
      run: |
        az webapp config appsettings set \
          --resource-group Personal \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --settings \
            SCM_DO_BUILD_DURING_DEPLOYMENT=false \
            ENABLE_ORYX_BUILD=false \
            DISABLE_COLLECTSTATIC=1

    # Deploy to single Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: deploy/