# GitHub Actions workflow for Azure deployment
name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_FRONTEND: 'shellhacks-frontend'
  AZURE_WEBAPP_NAME_BACKEND: 'shellhacks-backend'
  NODE_VERSION: '22.x'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Build React app
      run: |
        cd frontend
        npm run build

    - name: Copy server files
      run: |
        cp server.js frontend/
        cp package.json frontend/
        cp package-lock.json frontend/

    # ✅ ADD AZURE LOGIN STEP
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88FBF5A58CF4436E8F8955E200248A41 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7DE0416DFB4B4CB88EDDCA0CC26BC123 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AD05817C00C745649FDAAE35BB36A645 }}

    - name: Deploy to Azure Web App (Frontend)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
        package: frontend/

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment package
      run: |
        mkdir -p deploy
        
        # Copy Python files
        cp requirements.txt deploy/
        cp -r backend/* deploy/
        
        # Create startup script for Azure App Service
        cat > deploy/startup.sh << 'EOF'
        #!/bin/bash
        set -e
        echo "🚀 Starting FastAPI backend..."
        cd /home/site/wwwroot
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m uvicorn main:app --host 0.0.0.0 --port 8000
        EOF
        
        chmod +x deploy/startup.sh

    # ✅ ADD AZURE LOGIN STEP
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88FBF5A58CF4436E8F8955E200248A41 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7DE0416DFB4B4CB88EDDCA0CC26BC123 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AD05817C00C745649FDAAE35BB36A645 }}

    - name: Deploy to Azure Web App (Backend)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
        package: deploy/
        startup-command: './startup.sh'